/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#470e00',
        'on-primary': '#ffefeb',
        'on-surface': '#2f2f2e',
        background: '#f9f6f5',
        'secondary-container': '#ffc3c0',
        'primary-fixed-dim': '#ff5d2b',
        'outline-variant': '#afadac',
        'on-surface-variant': '#5c5b5b',
        'on-background': '#2f2f2e',
        'surface-bright': '#f9f6f5',
        'surface-container-high': '#e4e2e1',
        'surface-container-lowest': '#ffffff',
        primary: '#ab2d00',
        'tertiary-container': '#e699fd',
        'inverse-on-surface': '#9e9c9c',
        'on-secondary': '#ffefee',
        tertiary: '#833e9a',
        surface: '#f9f6f5',
        error: '#b31b25',
        'surface-dim': '#d6d4d3',
        'inverse-primary': '#ff5722',
        outline: '#787676',
        'surface-container-highest': '#dfdcdc',
        'on-tertiary': '#ffedfe',
        'primary-container': '#ff7851',
        'surface-container-low': '#f3f0ef',
        'surface-tint': '#ab2d00',
        'surface-container': '#eae7e7',
        'inverse-surface': '#0e0e0e',
        'primary-fixed': '#ff7851',
        secondary: '#a03739',
        'surface-variant': '#dfdcdc',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

